### ISSUE TITLE
O tweet em si é o melhor lugar para se avisar sobre ser uma IA?

### ISSUE THREAD

**Issue by Nick-Gabe** [SoUmNerd/ChoqueiDaBolhaDev#1]
Acho que seria interessante talvez manter essa info na bio da página para não soar tão redundante em todo tweet.
Pois o próprio twitter (x 🙄) mostra um badge dizendo que a conta é automatizada, o que dá a entender que não é um humano por trás daquilo. Então no meu ponto de vista adicionar o "🚨 Post gerado por IA sem revisão. Pode ter informações falsas. Caso algum problema, favor contatar no direct" não é necessário.

**Comment by JoaquimCassano** [comment]
Editado no código. Só que tá dando conflito aqui, tô tentando resolver pra commitar
